# Generated by Django 4.1 on 2023-10-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="products/"),
        ),
    ]
